name: Linting

on:
  push:
    branches:
      - main
      - develop
      - trunk
  pull_request:
    branches:
      - main
      - develop

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
      - name: WPCS check
        uses: 10up/wpcs-action@stable
        with:
          standard: 'WordPress'
