name: Linting

on:
  push:
    branches:
      - main
      - develop
      - trunk
  pull_request:
    branches:
      - main
      - develop

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Changed files
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          all:
            - '/'
    - name: WPCS check
      uses: 10up/wpcs-action@feature/phpcs-only-changed-files
      with:
        standard: 'WordPress'
